# Use the official Jekyll image
FROM bretfisher/jekyll-serve

# Set working directory
WORKDIR /site

# Copy updated site location into the container
COPY docs/site /site

# Optional: install missing dependencies (like libcurl4)
RUN apt-get update && apt-get install -y libcurl4

# Install Ruby gems defined in the Gemfile
RUN bundle install --retry 5 --jobs 20

# Use default entrypoint provided by the base image
ENTRYPOINT ["docker-entrypoint.sh"]

# Serve the site
CMD ["bundle", "exec", "jekyll", "serve", "--verbose", "--trace", "--force_polling", "-H", "0.0.0.0", "-P", "4000"]
