name: Docker Build Test

on:
  push:
    paths-ignore:
      - 'llmcode/website/**'
      - 'README.md'
      - 'HISTORY.md'
      - '.github/workflows/*'
      - '!.github/workflows/docker-build-test.yml'
    branches:
      - neopilot

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

  pull_request:
    paths-ignore:
      - 'llmcode/website/**'
      - 'README.md'
      - 'HISTORY.md'
      - '.github/workflows/*'
      - '!.github/workflows/docker-build-test.yml'
    branches:
      - main

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images (PR)
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        target: llmcode

    - name: Build Docker images (Push)
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.actor }}/llmcode:dev
        target: llmcode

    - name: Build Docker full image (PR)
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        target: llmcode-full

    - name: Build Docker full image (Push)
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.actor }}/llmcode-full:dev
        target: llmcode-full
